[package]
name = "fystan"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
clap = { version = "4.5.4", features = ["derive"] }
inkwell = { version = "0.4.0", features = ["llvm17-0"] }
target-lexicon = "0.13.2"

[profile.release]
opt-level = 3

[dev-dependencies]
tempfile = "3.20.0"