[package]
name = "fystan"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
clap = { version = "4.5.46", features = ["derive"] }
llvm-sys = { version = "180", features = ["prefer-dynamic"] }
target-lexicon = "0.13.2"

[profile.release]
opt-level = 3

[dev-dependencies]
tempfile = "3.21.0"
