[package]
name = "fystan"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
cranelift = "0.122.0"
cranelift-module = "0.122.0"
cranelift-object = "0.122.0"
clap = { version = "4.5.4", features = ["derive"] }
object = { version = "0.36.0", features = ["write"] }
target-lexicon = "0.13.2"

[profile.release]
opt-level = 3

[dev-dependencies]
tempfile = "3.20.0"