[package]
name = "fystan"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
clap = { version = "*", features = ["derive"] }
inkwell = { version = "*", features = ["llvm18-1"] }
target-lexicon = "*"

[profile.release]
opt-level = 3

[dev-dependencies]
tempfile = "*"